const express = require('express')
const router = express.Router()
const apiUsageLogRouter = require('./ApiUsageLog')
const categoryRouter = require('./Category')
const feedbackRouter = require('./Feedback')
const footProfileRouter = require('./FootProfile')
const productRouter = require('./Product')
const productVariantRouter = require('./ProductVariant')
const promptTemplateRouter = require('./PromptTemplate')
const renderJobRouter = require('./RenderJob')
const renderRatingRouter = require('./RenderRating')
const storeRouter = require('./Store')
const tokenRouter = require('./Token')
const userRouter = require('./User')
const userImageRouter = require('./UserImage')
const AuthRouter = require('./Auth')
const GuestRouter = require('./Guest')
router.use('/apiUsageLogs', apiUsageLogRouter)
router.use('/categories', categoryRouter)
router.use('/feedbacks', feedbackRouter)
router.use('/footProfiles', footProfileRouter)
router.use('/products', productRouter)
router.use('/variants', productVariantRouter)
router.use('/promptTemplates', promptTemplateRouter)
router.use('/renders', renderJobRouter)
router.use('/renderRatings', renderRatingRouter)
router.use('/stores', storeRouter)
router.use('/tokens', tokenRouter)
router.use('/users', userRouter)
router.use('/userImages', userImageRouter)
router.use('/auth', AuthRouter)
router.use('/guest', GuestRouter)
module.exports = router
